version: '3.8'

services:
  discordbot:
    build:
      context: .  # Path to your Dockerfile
    volumes:
      - .:/usr/app  # Mount the current directory to /usr/app in the container
    environment:
      - DISCORD_API_KEY=${DISCORD_API_KEY}  # Pass environment variables if needed
    command: watchmedo auto-restart --pattern="*.py" -- python discordbot.py  # Use watchmedo for auto-restart
